CREATE TABLE DOCTOR (
    ID NUMBER PRIMARY KEY,
    NAME VARCHAR2(50),
    SALARY NUMBER
);

CREATE TABLE PATIENT (
    ID NUMBER PRIMARY KEY,
    NAME VARCHAR2(50),
    AGE NUMBER
);

CREATE TABLE DOCTOR_PATIENT (
    DOCTOR_ID NUMBER,
    PATIENT_ID NUMBER,

    CONSTRAINT DOCTOR_PATIENT_PK
        PRIMARY KEY (DOCTOR_ID, PATIENT_ID),

    CONSTRAINT DOCTOR_FK
        FOREIGN KEY (DOCTOR_ID)
        REFERENCES DOCTOR(ID),

    CONSTRAINT PATIENT_FK
        FOREIGN KEY (PATIENT_ID)
        REFERENCES PATIENT(ID)
);