CREATE TABLE LANGUAGE (
    ID NUMBER PRIMARY KEY,
    NAME VARCHAR2(50)
);

CREATE TABLE TEACHER (
    ID NUMBER PRIMARY KEY,
    NAME VARCHAR2(50),
    SALARY NUMBER,
    LANGUAGE_ID NUMBER,

    CONSTRAINT TEACHER_LANGUAGE_FK
        FOREIGN KEY (LANGUAGE_ID)
        REFERENCES LANGUAGE(ID)
);