CREATE TABLE PHONE (
    ID NUMBER PRIMARY KEY,
    PHONENUMBER VARCHAR2(20)
);

CREATE TABLE EMPLOYEE (
    ID NUMBER PRIMARY KEY,
    NAME VARCHAR2(50),
    AGE NUMBER,
    PHONE_ID NUMBER UNIQUE,

    CONSTRAINT EMPLOYEE_PHONE_FK
        FOREIGN KEY (PHONE_ID)
        REFERENCES PHONE(ID)
);