-- ==========================================================
-- Question 1
-- Retrieve all employees and their department names
-- using LEFT OUTER JOIN
-- ==========================================================

CREATE TABLE DEPARTMENTS (
    DEPARTMENT_ID NUMBER PRIMARY KEY,
    DEPARTMENT_NAME VARCHAR2(50)
);

CREATE TABLE EMPLOYEES (
    EMPLOYEE_ID NUMBER PRIMARY KEY,
    EMPLOYEE_NAME VARCHAR2(50),
    DEPARTMENT_ID NUMBER
);

INSERT INTO DEPARTMENTS VALUES (10,'HR');
INSERT INTO DEPARTMENTS VALUES (20,'IT');

INSERT INTO EMPLOYEES VALUES (101,'Ahmed',10);
INSERT INTO EMPLOYEES VALUES (102,'Sara',20);
INSERT INTO EMPLOYEES VALUES (103,'Ali',NULL);

SELECT EMPLOYEE_NAME,
       DEPARTMENT_NAME
FROM EMPLOYEES
LEFT OUTER JOIN DEPARTMENTS
ON EMPLOYEES.DEPARTMENT_ID = DEPARTMENTS.DEPARTMENT_ID;


-- ==========================================================
-- Question 2
-- List all products and their associated categories
-- using LEFT OUTER JOIN
-- ==========================================================

CREATE TABLE CATEGORIES (
    CATEGORY_ID NUMBER PRIMARY KEY,
    CATEGORY_NAME VARCHAR2(50)
);

CREATE TABLE PRODUCTS (
    PRODUCT_ID NUMBER PRIMARY KEY,
    PRODUCT_NAME VARCHAR2(50),
    CATEGORY_ID NUMBER
);

INSERT INTO CATEGORIES VALUES (1,'Electronics');
INSERT INTO CATEGORIES VALUES (2,'Furniture');

INSERT INTO PRODUCTS VALUES (101,'Laptop',1);
INSERT INTO PRODUCTS VALUES (102,'Chair',2);
INSERT INTO PRODUCTS VALUES (103,'Phone',NULL);

SELECT PRODUCT_NAME,
       CATEGORY_NAME
FROM PRODUCTS
LEFT OUTER JOIN CATEGORIES
ON PRODUCTS.CATEGORY_ID = CATEGORIES.CATEGORY_ID;


-- ==========================================================
-- Question 3
-- Find all students and the courses they are enrolled in
-- using LEFT OUTER JOIN
-- ==========================================================

CREATE TABLE COURSES (
    COURSE_ID NUMBER PRIMARY KEY,
    COURSE_NAME VARCHAR2(50)
);

CREATE TABLE STUDENTS (
    STUDENT_ID NUMBER PRIMARY KEY,
    STUDENT_NAME VARCHAR2(50),
    COURSE_ID NUMBER
);

INSERT INTO COURSES VALUES (1,'Java');
INSERT INTO COURSES VALUES (2,'Oracle');

INSERT INTO STUDENTS VALUES (101,'Omar',1);
INSERT INTO STUDENTS VALUES (102,'Mona',2);
INSERT INTO STUDENTS VALUES (103,'Ali',NULL);

SELECT STUDENT_NAME,
       COURSE_NAME
FROM STUDENTS
LEFT OUTER JOIN COURSES
ON STUDENTS.COURSE_ID = COURSES.COURSE_ID;


-- ==========================================================
-- Question 4
-- Display all orders with customer names
-- using LEFT OUTER JOIN
-- ==========================================================

CREATE TABLE CUSTOMERS (
    CUSTOMER_ID NUMBER PRIMARY KEY,
    CUSTOMER_NAME VARCHAR2(50)
);

CREATE TABLE ORDERS (
    ORDER_ID NUMBER PRIMARY KEY,
    CUSTOMER_ID NUMBER
);

INSERT INTO CUSTOMERS VALUES (1,'Ahmed');
INSERT INTO CUSTOMERS VALUES (2,'Sara');

INSERT INTO ORDERS VALUES (101,1);
INSERT INTO ORDERS VALUES (102,2);
INSERT INTO ORDERS VALUES (103,NULL);

SELECT ORDER_ID,
       CUSTOMER_NAME
FROM ORDERS
LEFT OUTER JOIN CUSTOMERS
ON ORDERS.CUSTOMER_ID = CUSTOMERS.CUSTOMER_ID;


-- ==========================================================
-- Question 5
-- Show all departments and their managers
-- using LEFT OUTER JOIN
-- ==========================================================

CREATE TABLE MANAGERS (
    MANAGER_ID NUMBER PRIMARY KEY,
    MANAGER_NAME VARCHAR2(50)
);

CREATE TABLE DEPARTMENTS2 (
    DEPARTMENT_ID NUMBER PRIMARY KEY,
    DEPARTMENT_NAME VARCHAR2(50),
    MANAGER_ID NUMBER
);

INSERT INTO MANAGERS VALUES (1,'Mohamed');
INSERT INTO MANAGERS VALUES (2,'Khaled');

INSERT INTO DEPARTMENTS2 VALUES (10,'HR',1);
INSERT INTO DEPARTMENTS2 VALUES (20,'IT',2);
INSERT INTO DEPARTMENTS2 VALUES (30,'Finance',NULL);

SELECT DEPARTMENT_NAME,
       MANAGER_NAME
FROM DEPARTMENTS2
LEFT OUTER JOIN MANAGERS
ON DEPARTMENTS2.MANAGER_ID = MANAGERS.MANAGER_ID;


-- ==========================================================
-- Question 6
-- List all books and their authors
-- using LEFT OUTER JOIN
-- ==========================================================

CREATE TABLE AUTHORS (
    AUTHOR_ID NUMBER PRIMARY KEY,
    AUTHOR_NAME VARCHAR2(50)
);

CREATE TABLE BOOKS (
    BOOK_ID NUMBER PRIMARY KEY,
    BOOK_TITLE VARCHAR2(50),
    AUTHOR_ID NUMBER
);

INSERT INTO AUTHORS VALUES (1,'Naguib Mahfouz');
INSERT INTO AUTHORS VALUES (2,'Taha Hussein');

INSERT INTO BOOKS VALUES (101,'Palace Walk',1);
INSERT INTO BOOKS VALUES (102,'The Days',2);
INSERT INTO BOOKS VALUES (103,'Unknown Book',NULL);

SELECT BOOK_TITLE,
       AUTHOR_NAME
FROM BOOKS
LEFT OUTER JOIN AUTHORS
ON BOOKS.AUTHOR_ID = AUTHORS.AUTHOR_ID;


-- ==========================================================
-- Question 7
-- Retrieve all invoices with their payment status
-- using LEFT OUTER JOIN
-- ==========================================================

CREATE TABLE PAYMENTS (
    PAYMENT_ID NUMBER PRIMARY KEY,
    PAYMENT_STATUS VARCHAR2(30),
    INVOICE_ID NUMBER
);

CREATE TABLE INVOICES (
    INVOICE_ID NUMBER PRIMARY KEY,
    INVOICE_DATE DATE
);

INSERT INTO INVOICES VALUES (1001,SYSDATE);
INSERT INTO INVOICES VALUES (1002,SYSDATE);
INSERT INTO INVOICES VALUES (1003,SYSDATE);

INSERT INTO PAYMENTS VALUES (1,'Paid',1001);
INSERT INTO PAYMENTS VALUES (2,'Pending',1002);

SELECT INVOICE_ID,
       PAYMENT_STATUS
FROM INVOICES
LEFT OUTER JOIN PAYMENTS
ON INVOICES.INVOICE_ID = PAYMENTS.INVOICE_ID;


-- ==========================================================
-- Question 8
-- Get all employees and their projects
-- using LEFT OUTER JOIN
-- ==========================================================

CREATE TABLE EMPLOYEES2 (
    EMPLOYEE_ID NUMBER PRIMARY KEY,
    EMPLOYEE_NAME VARCHAR2(50)
);

CREATE TABLE PROJECTS_ASSIGNED (
    PROJECT_ID NUMBER PRIMARY KEY,
    PROJECT_NAME VARCHAR2(50),
    EMPLOYEE_ID NUMBER
);

INSERT INTO EMPLOYEES2 VALUES (1,'Ahmed');
INSERT INTO EMPLOYEES2 VALUES (2,'Sara');
INSERT INTO EMPLOYEES2 VALUES (3,'Ali');

INSERT INTO PROJECTS_ASSIGNED VALUES (101,'Bank System',1);
INSERT INTO PROJECTS_ASSIGNED VALUES (102,'Hospital System',2);

SELECT EMPLOYEE_NAME,
       PROJECT_NAME
FROM EMPLOYEES2
LEFT OUTER JOIN PROJECTS_ASSIGNED
ON EMPLOYEES2.EMPLOYEE_ID = PROJECTS_ASSIGNED.EMPLOYEE_ID;