-- ==========================================================
-- Question 1
-- List all customers and all orders.
-- Use FULL OUTER JOIN
-- ==========================================================

CREATE TABLE CUSTOMERS (
    CUSTOMER_ID NUMBER PRIMARY KEY,
    CUSTOMER_NAME VARCHAR2(50)
);

CREATE TABLE ORDERS (
    ORDER_ID NUMBER PRIMARY KEY,
    CUSTOMER_ID NUMBER
);

INSERT INTO CUSTOMERS VALUES (1,'Ahmed');
INSERT INTO CUSTOMERS VALUES (2,'Sara');
INSERT INTO CUSTOMERS VALUES (3,'Ali');

INSERT INTO ORDERS VALUES (101,1);
INSERT INTO ORDERS VALUES (102,2);
INSERT INTO ORDERS VALUES (103,5);

SELECT CUSTOMER_NAME,
       ORDER_ID
FROM CUSTOMERS
FULL OUTER JOIN ORDERS
ON CUSTOMERS.CUSTOMER_ID = ORDERS.CUSTOMER_ID;


-- ==========================================================
-- Question 2
-- Display all employees and all projects.
-- Use FULL OUTER JOIN
-- ==========================================================

CREATE TABLE EMPLOYEES (
    EMPLOYEE_ID NUMBER PRIMARY KEY,
    EMPLOYEE_NAME VARCHAR2(50),
    PROJECT_ID NUMBER
);

CREATE TABLE PROJECTS (
    PROJECT_ID NUMBER PRIMARY KEY,
    PROJECT_NAME VARCHAR2(50)
);

INSERT INTO EMPLOYEES VALUES (101,'Ahmed',1);
INSERT INTO EMPLOYEES VALUES (102,'Sara',2);
INSERT INTO EMPLOYEES VALUES (103,'Ali',NULL);

INSERT INTO PROJECTS VALUES (1,'Bank System');
INSERT INTO PROJECTS VALUES (2,'Hospital System');
INSERT INTO PROJECTS VALUES (3,'School System');

SELECT EMPLOYEE_NAME,
       PROJECT_NAME
FROM EMPLOYEES
FULL OUTER JOIN PROJECTS
ON EMPLOYEES.PROJECT_ID = PROJECTS.PROJECT_ID;


-- ==========================================================
-- Question 3
-- Show all products and all suppliers.
-- Use FULL OUTER JOIN
-- ==========================================================

CREATE TABLE SUPPLIERS (
    SUPPLIER_ID NUMBER PRIMARY KEY,
    SUPPLIER_NAME VARCHAR2(50)
);

CREATE TABLE PRODUCTS (
    PRODUCT_ID NUMBER PRIMARY KEY,
    PRODUCT_NAME VARCHAR2(50),
    SUPPLIER_ID NUMBER
);

INSERT INTO SUPPLIERS VALUES (1,'Dell');
INSERT INTO SUPPLIERS VALUES (2,'HP');
INSERT INTO SUPPLIERS VALUES (3,'Lenovo');

INSERT INTO PRODUCTS VALUES (101,'Laptop',1);
INSERT INTO PRODUCTS VALUES (102,'Printer',2);
INSERT INTO PRODUCTS VALUES (103,'Mouse',NULL);

SELECT PRODUCT_NAME,
       SUPPLIER_NAME
FROM PRODUCTS
FULL OUTER JOIN SUPPLIERS
ON PRODUCTS.SUPPLIER_ID = SUPPLIERS.SUPPLIER_ID;


-- ==========================================================
-- Question 4
-- List all students and all courses.
-- Use FULL OUTER JOIN
-- ==========================================================

CREATE TABLE COURSES (
    COURSE_ID NUMBER PRIMARY KEY,
    COURSE_NAME VARCHAR2(50)
);

CREATE TABLE STUDENTS (
    STUDENT_ID NUMBER PRIMARY KEY,
    STUDENT_NAME VARCHAR2(50),
    COURSE_ID NUMBER
);

INSERT INTO COURSES VALUES (1,'Java');
INSERT INTO COURSES VALUES (2,'Oracle');
INSERT INTO COURSES VALUES (3,'Spring');

INSERT INTO STUDENTS VALUES (101,'Omar',1);
INSERT INTO STUDENTS VALUES (102,'Mona',2);
INSERT INTO STUDENTS VALUES (103,'Ali',NULL);

SELECT STUDENT_NAME,
       COURSE_NAME
FROM STUDENTS
FULL OUTER JOIN COURSES
ON STUDENTS.COURSE_ID = COURSES.COURSE_ID;


-- ==========================================================
-- Question 5
-- Retrieve all authors and all books.
-- Use FULL OUTER JOIN
-- ==========================================================

CREATE TABLE AUTHORS (
    AUTHOR_ID NUMBER PRIMARY KEY,
    AUTHOR_NAME VARCHAR2(50)
);

CREATE TABLE BOOKS (
    BOOK_ID NUMBER PRIMARY KEY,
    BOOK_TITLE VARCHAR2(50),
    AUTHOR_ID NUMBER
);

INSERT INTO AUTHORS VALUES (1,'Naguib Mahfouz');
INSERT INTO AUTHORS VALUES (2,'Taha Hussein');
INSERT INTO AUTHORS VALUES (3,'Ahmed Khaled Tawfik');

INSERT INTO BOOKS VALUES (101,'Palace Walk',1);
INSERT INTO BOOKS VALUES (102,'The Days',2);
INSERT INTO BOOKS VALUES (103,'Unknown Book',NULL);

SELECT AUTHOR_NAME,
       BOOK_TITLE
FROM AUTHORS
FULL OUTER JOIN BOOKS
ON AUTHORS.AUTHOR_ID = BOOKS.AUTHOR_ID;


-- ==========================================================
-- Question 6
-- Find all employees and all departments.
-- Use FULL OUTER JOIN
-- ==========================================================

CREATE TABLE DEPARTMENTS (
    DEPARTMENT_ID NUMBER PRIMARY KEY,
    DEPARTMENT_NAME VARCHAR2(50)
);

CREATE TABLE EMPLOYEES2 (
    EMPLOYEE_ID NUMBER PRIMARY KEY,
    EMPLOYEE_NAME VARCHAR2(50),
    DEPARTMENT_ID NUMBER
);

INSERT INTO DEPARTMENTS VALUES (10,'HR');
INSERT INTO DEPARTMENTS VALUES (20,'IT');
INSERT INTO DEPARTMENTS VALUES (30,'Finance');

INSERT INTO EMPLOYEES2 VALUES (101,'Ahmed',10);
INSERT INTO EMPLOYEES2 VALUES (102,'Sara',20);
INSERT INTO EMPLOYEES2 VALUES (103,'Ali',NULL);

SELECT EMPLOYEE_NAME,
       DEPARTMENT_NAME
FROM EMPLOYEES2
FULL OUTER JOIN DEPARTMENTS
ON EMPLOYEES2.DEPARTMENT_ID = DEPARTMENTS.DEPARTMENT_ID;


-- ==========================================================
-- Question 7
-- Show all transactions and all payment methods.
-- Use FULL OUTER JOIN
-- ==========================================================

CREATE TABLE PAYMENT_METHODS (
    METHOD_ID NUMBER PRIMARY KEY,
    METHOD_NAME VARCHAR2(50)
);

CREATE TABLE TRANSACTIONS (
    TRANSACTION_ID NUMBER PRIMARY KEY,
    METHOD_ID NUMBER,
    AMOUNT NUMBER
);

INSERT INTO PAYMENT_METHODS VALUES (1,'Cash');
INSERT INTO PAYMENT_METHODS VALUES (2,'Visa');
INSERT INTO PAYMENT_METHODS VALUES (3,'PayPal');

INSERT INTO TRANSACTIONS VALUES (101,1,500);
INSERT INTO TRANSACTIONS VALUES (102,2,1000);
INSERT INTO TRANSACTIONS VALUES (103,NULL,250);

SELECT TRANSACTION_ID,
       AMOUNT,
       METHOD_NAME
FROM TRANSACTIONS
FULL OUTER JOIN PAYMENT_METHODS
ON TRANSACTIONS.METHOD_ID = PAYMENT_METHODS.METHOD_ID;


-- ==========================================================
-- Question 8
-- Combine two customer lists from two different regions.
-- Use FULL OUTER JOIN
-- ==========================================================

CREATE TABLE CUSTOMERS_REGION1 (
    CUSTOMER_ID NUMBER PRIMARY KEY,
    CUSTOMER_NAME VARCHAR2(50)
);

CREATE TABLE CUSTOMERS_REGION2 (
    CUSTOMER_ID NUMBER PRIMARY KEY,
    CUSTOMER_NAME VARCHAR2(50)
);

INSERT INTO CUSTOMERS_REGION1 VALUES (1,'Ahmed');
INSERT INTO CUSTOMERS_REGION1 VALUES (2,'Sara');

INSERT INTO CUSTOMERS_REGION2 VALUES (2,'Sara');
INSERT INTO CUSTOMERS_REGION2 VALUES (3,'Ali');

SELECT R1.CUSTOMER_NAME AS REGION1_CUSTOMER,
       R2.CUSTOMER_NAME AS REGION2_CUSTOMER
FROM CUSTOMERS_REGION1 R1
FULL OUTER JOIN CUSTOMERS_REGION2 R2
ON R1.CUSTOMER_ID = R2.CUSTOMER_ID;